name: dominos_counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2+1
  tflite_flutter: ^0.12.1
  image: ^4.8.0
  ultralytics_yolo: ^0.2.0
  wakelock_plus: ^1.4.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/model/
    
